### PR TITLE
provides an example of how to import the api functions

### PR DESCRIPTION
**Pull request by MiTo0o**

### CODE REVIEW

**Review by brotatotes — CHANGES_REQUESTED** [review]
What does this PR do? Please fix the PR title.

**Comment by MiTo0o** [comment]
provides an exmple of how to import the api fucntions

**Review by brotatotes — CHANGES_REQUESTED** [review]
Please update the title.

**Review by lulu-sun — APPROVED** [review]
good job

**Review by brotatotes — CHANGES_REQUESTED** [review]
image

**Review by brotatotes — APPROVED** [review]

**Pull request merged**
